name: "build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.11", "pypy-3.9"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: maxim-lobanov/setup-xcode@v1
      if: matrix.platform == 'macos-latest'
      with:
        xcode-version: 'latest'
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Build and install
      run: pip install --verbose '.[dev]'
    - name: Test
      run: pytest
    - name: Check that stubs are up-to-date
      run: |
        ./generate_stubs.sh
        git diff --exit-code || (echo "Stubs are out of date. Please run the ./generate_stubs.sh script." && exit 1)
