name: "build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-13, ubuntu-latest]
        python-version: ["3.10", "pypy-3.8"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: maxim-lobanov/setup-xcode@v1
      if: matrix.platform == 'macos-13'
      with:
        xcode-version: '14.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Build and install
      run: pip install --verbose .
    - name: Test
      run: pytest
